config/routes.rb
Blog::Application.routes.draw do
  root to: 'cats#index'

  resources :cats
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates_presence_of :no_legs
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :cat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find params[:id]
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find params[:id]
  end

  def update
    @cat = Cat.find params[:id]
    if cat.update(cat_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    Cat.find(params[:id]).destroy
    redirect_to root_path
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :no_legs)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_form.html.erb
<%= form_for @cat do |form| %>
  <p><%= @cat.errors.full_messages.inspect %></p>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :no_legs %>
  <%= form.text_field :no_legs %>

  <%= form.submit %>
<% end %>

app/views/cats/edit.html.erb
<h1>Edit a cat</h1>

<%= render 'form' %>

app/views/cats/index.html.erb
<h1>Cats</h1>

<ul>
  <% @cats.each do |cat| %>
    <li>
    <%= link_to cat.name, cat_path(cat) %>, <%= cat.no_legs %>
    </li>
  <% end %>
</ul>

app/views/cats/new.html.erb
<h1>Create a cat</h1>

<%= render 'form' %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<%= link_to "Delete", cat_path(@cat), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>